### PR TITLE
follow requests are POST now

### PR DESCRIPTION
**Pull request by nilsding**
related to swmff/xsu-authman#1

### CODE REVIEW

**Comment by trisuaso** [comment]
wow you're insanely fast I didn't even finish moving things yet!

anywho, everything looks perfect, thanks!

**Review by trisuaso — APPROVED** [review]

**Comment by nilsding** [comment]
yeah, i got confused at why the repo suddenly was missing files x)

**Comment by trisuaso** [comment]
it *should* be good now! everything was previously one big monorepo and it started to get awful since it shared it with 13 other crates...

**Comment by nilsding** [comment]
well, now it's time to get used to submodules then :D 

the `xsu-authman` one still needs an update in here, otherwise follows/unfollows won't work

**Comment by trisuaso** [comment]
I hate submodules too, just slightly less

still easier than publishing the package each time and bumping versions

**Pull request merged**
